name: The First Pulse  
on: [push]  
jobs:  
  test-runner:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Print Status  
        run: echo "The Conveyor Belt is Operational. Hello DevSecOps!" 